### ISSUE TITLE
Deprecated functions

### ISSUE THREAD

**Issue by NunoMiguelVeloso** [calvium/react-native-redux-connectivity#1]
Getting yellow warnings for deprecated functions on NetInfo.
![screen shot 2017-10-02 at 12 02 46](https://user-images.githubusercontent.com/10160597/31074678-b973649c-a769-11e7-96e8-3e033c4e1d95.png)

**Comment by pablocarrillo** [comment]
Should be an straightforward change, but we must annotate the versions of RN that will be compatible after the update

**Comment by benvium** [comment]
@pablocarrillo good point. We're using this is some pretty old RN versions, e.g. .39.

**Comment by benvium** [comment]
I just checked and NetInfo.fetch() is deprecated in .48, so if we upgrade this we'll need to mark the new version as RN 48+ only.

**Comment by benvium** [comment]
This is covered by #2
