### ISSUE TITLE
Update NetInfo Access, Retrieve from @react-native-community/netinfo

### ISSUE THREAD

**Issue by mazenchami** [calvium/react-native-redux-connectivity#3]
Hi,

I currently have a local branch with `NetInfo` access updated per RN deprecating it from the core library.

Can you please grant me permission to push my local branch to update this dependency or let me know what can be done to fix it?

Thanks,
-Mazen

**Comment by mattvot** [comment]
Hey @mazenchami, are you able to open a pull request?

**Comment by mazenchami** [comment]
@mattvot no. i'm not able to push my local branch up to open a PR. do you have permissions to help?

**Comment by pablocarrillo** [comment]
Hi @mazenchami you should be able to fork this repository, push your changes to the fork and open a pull request from there against our repo. This gist have an explanation of the process: https://gist.github.com/Chaser324/ce0505fbed06b947d962

**Comment by mazenchami** [comment]
@pablocarrillo thank you, i will follow those steps and create a PR

**Comment by mazenchami** [comment]
closing this issue as the [PR](https://github.com/calvium/react-native-redux-connectivity/pull/4) is now open
