### ISSUE TITLE
Deploy new version to npm

### ISSUE THREAD

**Issue by pablocarrillo** [calvium/react-native-redux-connectivity#5]
After #4 we should deploy a new version to NPM with:
- [x] A bumped version for the module
- [x] Revisit the peer dependencies versions
- [x] Add typescript declarations for the module

**Comment by mazenchami** [comment]
@pablocarrillo do you have a timeline for when this will be merged?

**Comment by mattvot** [comment]
Looks like it's released on npm as `0.2.0`: https://www.npmjs.com/package/react-native-redux-connectivity

**Comment by pablocarrillo** [comment]
yes, this has been already deployed as `0.2.0`
